// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type AbilityListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// AbilityList200ApplicationJSON - A list of abilities
type AbilityList200ApplicationJSON struct {
	// The total number of abilities available
	Count *int64 `json:"count,omitempty"`
	// The URL for the next page of abilities (null if none)
	Next *string `json:"next,omitempty"`
	// The URL for the previous page of abilities (null if none)
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Ability `json:"results,omitempty"`
}

type AbilityListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A list of abilities
	AbilityList200ApplicationJSONObject *AbilityList200ApplicationJSON
}
