// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFlavorListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *BerryFlavorListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *BerryFlavorListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// BerryFlavorListResponseBody - OK
type BerryFlavorListResponseBody struct {
	// The total number of berry flavors
	Count *int64 `json:"count,omitempty"`
	// The URL to the next page of berry flavors (if any)
	Next *string `json:"next,omitempty"`
	// The URL to the previous page of berry flavors (if any)
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.BerryFlavor `json:"results,omitempty"`
}

func (o *BerryFlavorListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *BerryFlavorListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *BerryFlavorListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *BerryFlavorListResponseBody) GetResults() []shared.BerryFlavor {
	if o == nil {
		return nil
	}
	return o.Results
}

type BerryFlavorListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *BerryFlavorListResponseBody
}

func (o *BerryFlavorListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BerryFlavorListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BerryFlavorListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BerryFlavorListResponse) GetObject() *BerryFlavorListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
