// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFlavorListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// BerryFlavorList200ApplicationJSON - OK
type BerryFlavorList200ApplicationJSON struct {
	// The total number of berry flavors
	Count *int64 `json:"count,omitempty"`
	// The URL to the next page of berry flavors (if any)
	Next *string `json:"next,omitempty"`
	// The URL to the previous page of berry flavors (if any)
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.BerryFlavor `json:"results,omitempty"`
}

type BerryFlavorListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	BerryFlavorList200ApplicationJSONObject *BerryFlavorList200ApplicationJSON
}
