// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFirmnessReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type BerryFirmnessReadResponse struct {
	// Successful response
	BerryFirmness *shared.BerryFirmness
	ContentType   string
	StatusCode    int
	RawResponse   *http.Response
}
