// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFirmnessListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *BerryFirmnessListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *BerryFirmnessListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// BerryFirmnessList200ApplicationJSON - OK
type BerryFirmnessList200ApplicationJSON struct {
	// The total number of berry firmnesses available from this API.
	Count *int64 `json:"count,omitempty"`
	// The URL for the next page of results, or null if there are no more results.
	Next *string `json:"next,omitempty"`
	// The URL for the previous page of results, or null if this is the first page.
	Previous *string                `json:"previous,omitempty"`
	Results  []shared.BerryFirmness `json:"results,omitempty"`
}

func (o *BerryFirmnessList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *BerryFirmnessList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *BerryFirmnessList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *BerryFirmnessList200ApplicationJSON) GetResults() []shared.BerryFirmness {
	if o == nil {
		return nil
	}
	return o.Results
}

type BerryFirmnessListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	BerryFirmnessList200ApplicationJSONObject *BerryFirmnessList200ApplicationJSON
}

func (o *BerryFirmnessListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BerryFirmnessListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BerryFirmnessListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BerryFirmnessListResponse) GetBerryFirmnessList200ApplicationJSONObject() *BerryFirmnessList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.BerryFirmnessList200ApplicationJSONObject
}
