// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFlavorReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *BerryFlavorReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type BerryFlavorReadResponse struct {
	// Successful response
	BerryFlavor *shared.BerryFlavor
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *BerryFlavorReadResponse) GetBerryFlavor() *shared.BerryFlavor {
	if o == nil {
		return nil
	}
	return o.BerryFlavor
}

func (o *BerryFlavorReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BerryFlavorReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BerryFlavorReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
