// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type BerryFlavorReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type BerryFlavorReadResponse struct {
	// Successful response
	BerryFlavor *shared.BerryFlavor
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
