// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ContestEffectListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ContestEffectList200ApplicationJSON - A list of contest effects
type ContestEffectList200ApplicationJSON struct {
	// The total number of contest effects
	Count *int64 `json:"count,omitempty"`
	// The URL to get the next page of contest effects (if it exists)
	Next *string `json:"next,omitempty"`
	// The URL to get the previous page of contest effects (if it exists)
	Previous *string                `json:"previous,omitempty"`
	Results  []shared.ContestEffect `json:"results,omitempty"`
}

type ContestEffectListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A list of contest effects
	ContestEffectList200ApplicationJSONObject *ContestEffectList200ApplicationJSON
}
