// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ContestTypeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ContestTypeListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ContestTypeListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ContestTypeListResponseBody - Successful response containing a list of contest types
type ContestTypeListResponseBody struct {
	// The total number of contest types returned
	Count *int64 `json:"count,omitempty"`
	// URL to the next page of contest types, if any
	Next *string `json:"next,omitempty"`
	// URL to the previous page of contest types, if any
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.ContestType `json:"results,omitempty"`
}

func (o *ContestTypeListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ContestTypeListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ContestTypeListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ContestTypeListResponseBody) GetResults() []shared.ContestType {
	if o == nil {
		return nil
	}
	return o.Results
}

type ContestTypeListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response containing a list of contest types
	Object *ContestTypeListResponseBody
}

func (o *ContestTypeListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ContestTypeListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ContestTypeListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ContestTypeListResponse) GetObject() *ContestTypeListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
