// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ContestEffectListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ContestEffectListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ContestEffectListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ContestEffectListResponseBody - A list of contest effects
type ContestEffectListResponseBody struct {
	// The total number of contest effects
	Count *int64 `json:"count,omitempty"`
	// The URL to get the next page of contest effects (if it exists)
	Next *string `json:"next,omitempty"`
	// The URL to get the previous page of contest effects (if it exists)
	Previous *string                `json:"previous,omitempty"`
	Results  []shared.ContestEffect `json:"results,omitempty"`
}

func (o *ContestEffectListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ContestEffectListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ContestEffectListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ContestEffectListResponseBody) GetResults() []shared.ContestEffect {
	if o == nil {
		return nil
	}
	return o.Results
}

type ContestEffectListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A list of contest effects
	Object *ContestEffectListResponseBody
}

func (o *ContestEffectListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ContestEffectListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ContestEffectListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ContestEffectListResponse) GetObject() *ContestEffectListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
