// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ContestTypeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ContestTypeList200ApplicationJSON - Successful response containing a list of contest types
type ContestTypeList200ApplicationJSON struct {
	// The total number of contest types returned
	Count *int64 `json:"count,omitempty"`
	// URL to the next page of contest types, if any
	Next *string `json:"next,omitempty"`
	// URL to the previous page of contest types, if any
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.ContestType `json:"results,omitempty"`
}

type ContestTypeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response containing a list of contest types
	ContestTypeList200ApplicationJSONObject *ContestTypeList200ApplicationJSON
}
