// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EggGroupReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *EggGroupReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type EggGroupReadResponse struct {
	ContentType string
	// Successful response
	EggGroup    *shared.EggGroup
	StatusCode  int
	RawResponse *http.Response
}

func (o *EggGroupReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EggGroupReadResponse) GetEggGroup() *shared.EggGroup {
	if o == nil {
		return nil
	}
	return o.EggGroup
}

func (o *EggGroupReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EggGroupReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
