// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterMethodReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *EncounterMethodReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type EncounterMethodReadResponse struct {
	ContentType string
	// Successful response
	EncounterMethod *shared.EncounterMethod
	StatusCode      int
	RawResponse     *http.Response
}

func (o *EncounterMethodReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EncounterMethodReadResponse) GetEncounterMethod() *shared.EncounterMethod {
	if o == nil {
		return nil
	}
	return o.EncounterMethod
}

func (o *EncounterMethodReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EncounterMethodReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
