// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterConditionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// EncounterConditionList200ApplicationJSON - OK
type EncounterConditionList200ApplicationJSON struct {
	// The total number of encounter conditions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of encounter conditions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of encounter conditions.
	Previous *string                     `json:"previous,omitempty"`
	Results  []shared.EncounterCondition `json:"results,omitempty"`
}

type EncounterConditionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	EncounterConditionList200ApplicationJSONObject *EncounterConditionList200ApplicationJSON
}
