// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterMethodListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// EncounterMethodList200ApplicationJSON - OK
type EncounterMethodList200ApplicationJSON struct {
	// The total number of encounter methods.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of encounter methods.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of encounter methods.
	Previous *string                  `json:"previous,omitempty"`
	Results  []shared.EncounterMethod `json:"results,omitempty"`
}

type EncounterMethodListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	EncounterMethodList200ApplicationJSONObject *EncounterMethodList200ApplicationJSON
}
