// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterMethodReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type EncounterMethodReadResponse struct {
	ContentType string
	// Successful response
	EncounterMethod *shared.EncounterMethod
	StatusCode      int
	RawResponse     *http.Response
}
