// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterConditionValueListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

type EncounterConditionValueListResponse struct {
	ContentType string
	// Successful response containing a list of encounter condition values
	EncounterConditionValues []shared.EncounterConditionValue
	StatusCode               int
	RawResponse              *http.Response
}
