// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EncounterConditionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *EncounterConditionListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *EncounterConditionListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// EncounterConditionList200ApplicationJSON - OK
type EncounterConditionList200ApplicationJSON struct {
	// The total number of encounter conditions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of encounter conditions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of encounter conditions.
	Previous *string                     `json:"previous,omitempty"`
	Results  []shared.EncounterCondition `json:"results,omitempty"`
}

func (o *EncounterConditionList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *EncounterConditionList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *EncounterConditionList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *EncounterConditionList200ApplicationJSON) GetResults() []shared.EncounterCondition {
	if o == nil {
		return nil
	}
	return o.Results
}

type EncounterConditionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	EncounterConditionList200ApplicationJSONObject *EncounterConditionList200ApplicationJSON
}

func (o *EncounterConditionListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EncounterConditionListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EncounterConditionListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EncounterConditionListResponse) GetEncounterConditionList200ApplicationJSONObject() *EncounterConditionList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.EncounterConditionList200ApplicationJSONObject
}
