// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EvolutionTriggerListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// EvolutionTriggerList200ApplicationJSON - OK
type EvolutionTriggerList200ApplicationJSON struct {
	// The total number of evolution triggers.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of evolution triggers.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of evolution triggers.
	Previous *string                   `json:"previous,omitempty"`
	Results  []shared.EvolutionTrigger `json:"results,omitempty"`
}

type EvolutionTriggerListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	EvolutionTriggerList200ApplicationJSONObject *EvolutionTriggerList200ApplicationJSON
}
