// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EvolutionTriggerReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *EvolutionTriggerReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type EvolutionTriggerReadResponse struct {
	ContentType string
	// Successful response
	EvolutionTrigger *shared.EvolutionTrigger
	StatusCode       int
	RawResponse      *http.Response
}

func (o *EvolutionTriggerReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EvolutionTriggerReadResponse) GetEvolutionTrigger() *shared.EvolutionTrigger {
	if o == nil {
		return nil
	}
	return o.EvolutionTrigger
}

func (o *EvolutionTriggerReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EvolutionTriggerReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
