// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type EvolutionTriggerListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *EvolutionTriggerListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *EvolutionTriggerListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// EvolutionTriggerListResponseBody - OK
type EvolutionTriggerListResponseBody struct {
	// The total number of evolution triggers.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of evolution triggers.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of evolution triggers.
	Previous *string                   `json:"previous,omitempty"`
	Results  []shared.EvolutionTrigger `json:"results,omitempty"`
}

func (o *EvolutionTriggerListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *EvolutionTriggerListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *EvolutionTriggerListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *EvolutionTriggerListResponseBody) GetResults() []shared.EvolutionTrigger {
	if o == nil {
		return nil
	}
	return o.Results
}

type EvolutionTriggerListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *EvolutionTriggerListResponseBody
}

func (o *EvolutionTriggerListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *EvolutionTriggerListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *EvolutionTriggerListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *EvolutionTriggerListResponse) GetObject() *EvolutionTriggerListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
