// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GenderListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// GenderList200ApplicationJSON - OK
type GenderList200ApplicationJSON struct {
	// The total number of genders.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of genders.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of genders.
	Previous *string         `json:"previous,omitempty"`
	Results  []shared.Gender `json:"results,omitempty"`
}

type GenderListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GenderList200ApplicationJSONObject *GenderList200ApplicationJSON
}
