// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GenerationReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GenerationReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type GenerationReadResponse struct {
	ContentType string
	// Successful response
	Generation  *shared.Generation
	StatusCode  int
	RawResponse *http.Response
}

func (o *GenerationReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GenerationReadResponse) GetGeneration() *shared.Generation {
	if o == nil {
		return nil
	}
	return o.Generation
}

func (o *GenerationReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GenerationReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
