// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GenerationReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type GenerationReadResponse struct {
	ContentType string
	// Successful response
	Generation  *shared.Generation
	StatusCode  int
	RawResponse *http.Response
}
