// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GenerationListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// GenerationList200ApplicationJSON - OK
type GenerationList200ApplicationJSON struct {
	// The total number of generations.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of generations.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of generations.
	Previous *string             `json:"previous,omitempty"`
	Results  []shared.Generation `json:"results,omitempty"`
}

type GenerationListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GenerationList200ApplicationJSONObject *GenerationList200ApplicationJSON
}
