// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GrowthRateListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *GrowthRateListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GrowthRateListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// GrowthRateList200ApplicationJSON - OK
type GrowthRateList200ApplicationJSON struct {
	// The total number of growth rates.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of growth rates.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of growth rates.
	Previous *string             `json:"previous,omitempty"`
	Results  []shared.GrowthRate `json:"results,omitempty"`
}

func (o *GrowthRateList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *GrowthRateList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GrowthRateList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *GrowthRateList200ApplicationJSON) GetResults() []shared.GrowthRate {
	if o == nil {
		return nil
	}
	return o.Results
}

type GrowthRateListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GrowthRateList200ApplicationJSONObject *GrowthRateList200ApplicationJSON
}

func (o *GrowthRateListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GrowthRateListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GrowthRateListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GrowthRateListResponse) GetGrowthRateList200ApplicationJSONObject() *GrowthRateList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.GrowthRateList200ApplicationJSONObject
}
