// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GrowthRateListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// GrowthRateList200ApplicationJSON - OK
type GrowthRateList200ApplicationJSON struct {
	// The total number of growth rates.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of growth rates.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of growth rates.
	Previous *string             `json:"previous,omitempty"`
	Results  []shared.GrowthRate `json:"results,omitempty"`
}

type GrowthRateListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GrowthRateList200ApplicationJSONObject *GrowthRateList200ApplicationJSON
}
