// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type GrowthRateReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GrowthRateReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type GrowthRateReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	GrowthRate *shared.GrowthRate
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GrowthRateReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GrowthRateReadResponse) GetGrowthRate() *shared.GrowthRate {
	if o == nil {
		return nil
	}
	return o.GrowthRate
}

func (o *GrowthRateReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GrowthRateReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
