// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemPocketReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type ItemPocketReadResponse struct {
	ContentType string
	// Successful response
	ItemPocket  *shared.ItemPocket
	StatusCode  int
	RawResponse *http.Response
}
