// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type ItemReadResponse struct {
	ContentType string
	// Successful response
	Item        *shared.Item
	StatusCode  int
	RawResponse *http.Response
}
