// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemAttributeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ItemAttributeList200ApplicationJSON - OK
type ItemAttributeList200ApplicationJSON struct {
	// The total number of item attributes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item attributes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item attributes.
	Previous *string                `json:"previous,omitempty"`
	Results  []shared.ItemAttribute `json:"results,omitempty"`
}

type ItemAttributeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemAttributeList200ApplicationJSONObject *ItemAttributeList200ApplicationJSON
}
