// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemFlingEffectListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ItemFlingEffectListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ItemFlingEffectListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ItemFlingEffectList200ApplicationJSON - OK
type ItemFlingEffectList200ApplicationJSON struct {
	// The total number of item fling effects.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item fling effects.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item fling effects.
	Previous *string                  `json:"previous,omitempty"`
	Results  []shared.ItemFlingEffect `json:"results,omitempty"`
}

func (o *ItemFlingEffectList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ItemFlingEffectList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ItemFlingEffectList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ItemFlingEffectList200ApplicationJSON) GetResults() []shared.ItemFlingEffect {
	if o == nil {
		return nil
	}
	return o.Results
}

type ItemFlingEffectListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemFlingEffectList200ApplicationJSONObject *ItemFlingEffectList200ApplicationJSON
}

func (o *ItemFlingEffectListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemFlingEffectListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemFlingEffectListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemFlingEffectListResponse) GetItemFlingEffectList200ApplicationJSONObject() *ItemFlingEffectList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ItemFlingEffectList200ApplicationJSONObject
}
