// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemCategoryReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type ItemCategoryReadResponse struct {
	ContentType string
	// Successful response
	ItemCategory *shared.ItemCategory
	StatusCode   int
	RawResponse  *http.Response
}
