// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemFlingEffectReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type ItemFlingEffectReadResponse struct {
	ContentType string
	// Successful response
	ItemFlingEffect *shared.ItemFlingEffect
	StatusCode      int
	RawResponse     *http.Response
}
