// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ItemListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ItemListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ItemList200ApplicationJSON - OK
type ItemList200ApplicationJSON struct {
	// The total number of items.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of items.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of items.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Item `json:"results,omitempty"`
}

func (o *ItemList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ItemList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ItemList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ItemList200ApplicationJSON) GetResults() []shared.Item {
	if o == nil {
		return nil
	}
	return o.Results
}

type ItemListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemList200ApplicationJSONObject *ItemList200ApplicationJSON
}

func (o *ItemListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemListResponse) GetItemList200ApplicationJSONObject() *ItemList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ItemList200ApplicationJSONObject
}
