// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ItemList200ApplicationJSON - OK
type ItemList200ApplicationJSON struct {
	// The total number of items.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of items.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of items.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Item `json:"results,omitempty"`
}

type ItemListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemList200ApplicationJSONObject *ItemList200ApplicationJSON
}
