// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemCategoryListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ItemCategoryList200ApplicationJSON - OK
type ItemCategoryList200ApplicationJSON struct {
	// The total number of item categories.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item categories.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item categories.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.ItemCategory `json:"results,omitempty"`
}

type ItemCategoryListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemCategoryList200ApplicationJSONObject *ItemCategoryList200ApplicationJSON
}
