// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemAttributeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ItemAttributeListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ItemAttributeListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ItemAttributeListResponseBody - OK
type ItemAttributeListResponseBody struct {
	// The total number of item attributes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item attributes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item attributes.
	Previous *string                `json:"previous,omitempty"`
	Results  []shared.ItemAttribute `json:"results,omitempty"`
}

func (o *ItemAttributeListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ItemAttributeListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ItemAttributeListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ItemAttributeListResponseBody) GetResults() []shared.ItemAttribute {
	if o == nil {
		return nil
	}
	return o.Results
}

type ItemAttributeListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *ItemAttributeListResponseBody
}

func (o *ItemAttributeListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemAttributeListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemAttributeListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemAttributeListResponse) GetObject() *ItemAttributeListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
