// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemPocketListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// ItemPocketList200ApplicationJSON - OK
type ItemPocketList200ApplicationJSON struct {
	// The total number of item pockets.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item pockets.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item pockets.
	Previous *string             `json:"previous,omitempty"`
	Results  []shared.ItemPocket `json:"results,omitempty"`
}

type ItemPocketListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ItemPocketList200ApplicationJSONObject *ItemPocketList200ApplicationJSON
}
