// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemAttributeReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type ItemAttributeReadResponse struct {
	ContentType string
	// Successful response
	ItemAttribute *shared.ItemAttribute
	StatusCode    int
	RawResponse   *http.Response
}
