// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type ItemCategoryListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *ItemCategoryListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ItemCategoryListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// ItemCategoryList200ApplicationJSON - OK
type ItemCategoryList200ApplicationJSON struct {
	// The total number of item categories.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of item categories.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of item categories.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.ItemCategory `json:"results,omitempty"`
}

func (o *ItemCategoryList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *ItemCategoryList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ItemCategoryList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ItemCategoryList200ApplicationJSON) GetResults() []shared.ItemCategory {
	if o == nil {
		return nil
	}
	return o.Results
}

type ItemCategoryListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ItemCategoryList200ApplicationJSONObject *ItemCategoryList200ApplicationJSON
}

func (o *ItemCategoryListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ItemCategoryListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ItemCategoryListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ItemCategoryListResponse) GetItemCategoryList200ApplicationJSONObject() *ItemCategoryList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ItemCategoryList200ApplicationJSONObject
}
