// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LanguageListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// LanguageList200ApplicationJSON - OK
type LanguageList200ApplicationJSON struct {
	// The total number of languages.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of languages.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of languages.
	Previous *string           `json:"previous,omitempty"`
	Results  []shared.Language `json:"results,omitempty"`
}

type LanguageListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LanguageList200ApplicationJSONObject *LanguageList200ApplicationJSON
}
