// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *LocationListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LocationListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// LocationListResponseBody - OK
type LocationListResponseBody struct {
	// The total number of locations.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of locations.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of locations.
	Previous *string           `json:"previous,omitempty"`
	Results  []shared.Location `json:"results,omitempty"`
}

func (o *LocationListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *LocationListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *LocationListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *LocationListResponseBody) GetResults() []shared.Location {
	if o == nil {
		return nil
	}
	return o.Results
}

type LocationListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *LocationListResponseBody
}

func (o *LocationListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LocationListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LocationListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LocationListResponse) GetObject() *LocationListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
