// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type LocationReadResponse struct {
	ContentType string
	// Successful response
	Location    *shared.Location
	StatusCode  int
	RawResponse *http.Response
}
