// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationAreaReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type LocationAreaReadResponse struct {
	ContentType string
	// Successful response
	LocationArea *shared.LocationArea
	StatusCode   int
	RawResponse  *http.Response
}
