// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationAreaListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// LocationAreaList200ApplicationJSON - OK
type LocationAreaList200ApplicationJSON struct {
	// The total number of location areas.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of location areas.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of location areas.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.LocationArea `json:"results,omitempty"`
}

type LocationAreaListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LocationAreaList200ApplicationJSONObject *LocationAreaList200ApplicationJSON
}
