// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationAreaListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *LocationAreaListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *LocationAreaListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// LocationAreaListResponseBody - OK
type LocationAreaListResponseBody struct {
	// The total number of location areas.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of location areas.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of location areas.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.LocationArea `json:"results,omitempty"`
}

func (o *LocationAreaListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *LocationAreaListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *LocationAreaListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *LocationAreaListResponseBody) GetResults() []shared.LocationArea {
	if o == nil {
		return nil
	}
	return o.Results
}

type LocationAreaListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *LocationAreaListResponseBody
}

func (o *LocationAreaListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LocationAreaListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LocationAreaListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LocationAreaListResponse) GetObject() *LocationAreaListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
