// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationAreaReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *LocationAreaReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type LocationAreaReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	LocationArea *shared.LocationArea
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *LocationAreaReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LocationAreaReadResponse) GetLocationArea() *shared.LocationArea {
	if o == nil {
		return nil
	}
	return o.LocationArea
}

func (o *LocationAreaReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LocationAreaReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
