// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type LocationListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// LocationList200ApplicationJSON - OK
type LocationList200ApplicationJSON struct {
	// The total number of locations.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of locations.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of locations.
	Previous *string           `json:"previous,omitempty"`
	Results  []shared.Location `json:"results,omitempty"`
}

type LocationListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LocationList200ApplicationJSONObject *LocationList200ApplicationJSON
}
