// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MachineListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// MachineList200ApplicationJSON - OK
type MachineList200ApplicationJSON struct {
	// The total number of machines.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of machines.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of machines.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Machine `json:"results,omitempty"`
}

type MachineListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	MachineList200ApplicationJSONObject *MachineList200ApplicationJSON
}
