// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MachineReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MachineReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MachineReadResponse struct {
	ContentType string
	// Successful response
	Machine     *shared.Machine
	StatusCode  int
	RawResponse *http.Response
}

func (o *MachineReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MachineReadResponse) GetMachine() *shared.Machine {
	if o == nil {
		return nil
	}
	return o.Machine
}

func (o *MachineReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MachineReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
