// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MachineListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *MachineListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *MachineListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// MachineList200ApplicationJSON - OK
type MachineList200ApplicationJSON struct {
	// The total number of machines.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of machines.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of machines.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Machine `json:"results,omitempty"`
}

func (o *MachineList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *MachineList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *MachineList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *MachineList200ApplicationJSON) GetResults() []shared.Machine {
	if o == nil {
		return nil
	}
	return o.Results
}

type MachineListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MachineList200ApplicationJSONObject *MachineList200ApplicationJSON
}

func (o *MachineListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MachineListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MachineListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MachineListResponse) GetMachineList200ApplicationJSONObject() *MachineList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.MachineList200ApplicationJSONObject
}
