// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveDamageClassListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *MoveDamageClassListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *MoveDamageClassListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// MoveDamageClassListResponseBody - OK
type MoveDamageClassListResponseBody struct {
	// The total number of move damage classes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of move damage classes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of move damage classes.
	Previous *string                  `json:"previous,omitempty"`
	Results  []shared.MoveDamageClass `json:"results,omitempty"`
}

func (o *MoveDamageClassListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *MoveDamageClassListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *MoveDamageClassListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *MoveDamageClassListResponseBody) GetResults() []shared.MoveDamageClass {
	if o == nil {
		return nil
	}
	return o.Results
}

type MoveDamageClassListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *MoveDamageClassListResponseBody
}

func (o *MoveDamageClassListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveDamageClassListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveDamageClassListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveDamageClassListResponse) GetObject() *MoveDamageClassListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
