// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *MoveListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *MoveListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// MoveListResponseBody - OK
type MoveListResponseBody struct {
	// The total number of moves.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of moves.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of moves.
	Previous *string            `json:"previous,omitempty"`
	Results  []shared.MoveInput `json:"results,omitempty"`
}

func (o *MoveListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *MoveListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *MoveListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *MoveListResponseBody) GetResults() []shared.MoveInput {
	if o == nil {
		return nil
	}
	return o.Results
}

type MoveListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *MoveListResponseBody
}

func (o *MoveListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *MoveListResponse) GetObject() *MoveListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
