// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type MoveReadResponse struct {
	ContentType string
	// Successful response
	Move        *shared.Move
	StatusCode  int
	RawResponse *http.Response
}
