// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveTargetReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type MoveTargetReadResponse struct {
	ContentType string
	// Successful response
	MoveTarget  *shared.MoveTarget1
	StatusCode  int
	RawResponse *http.Response
}
