// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveBattleStyleListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// MoveBattleStyleList200ApplicationJSON - OK
type MoveBattleStyleList200ApplicationJSON struct {
	// The total number of move battle styles.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of move battle styles.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of move battle styles.
	Previous *string                  `json:"previous,omitempty"`
	Results  []shared.MoveBattleStyle `json:"results,omitempty"`
}

type MoveBattleStyleListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	MoveBattleStyleList200ApplicationJSONObject *MoveBattleStyleList200ApplicationJSON
}
