// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveCategoryListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// MoveCategoryList200ApplicationJSON - OK
type MoveCategoryList200ApplicationJSON struct {
	// The total number of move categories.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of move categories.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of move categories.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.MoveCategory `json:"results,omitempty"`
}

type MoveCategoryListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	MoveCategoryList200ApplicationJSONObject *MoveCategoryList200ApplicationJSON
}
