// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveLearnMethodReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type MoveLearnMethodReadResponse struct {
	ContentType string
	// Successful response
	MoveLearnMethod *shared.MoveLearnMethod
	StatusCode      int
	RawResponse     *http.Response
}
