// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveTargetReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveTargetReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveTargetReadResponse struct {
	ContentType string
	// Successful response
	MoveTarget  *shared.MoveTarget1
	StatusCode  int
	RawResponse *http.Response
}

func (o *MoveTargetReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveTargetReadResponse) GetMoveTarget() *shared.MoveTarget1 {
	if o == nil {
		return nil
	}
	return o.MoveTarget
}

func (o *MoveTargetReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveTargetReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
