// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveBattleStyleReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type MoveBattleStyleReadResponse struct {
	ContentType string
	// Successful response
	MoveBattleStyle *shared.MoveBattleStyle
	StatusCode      int
	RawResponse     *http.Response
}
