// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveBattleStyleReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveBattleStyleReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveBattleStyleReadResponse struct {
	ContentType string
	// Successful response
	MoveBattleStyle *shared.MoveBattleStyle
	StatusCode      int
	RawResponse     *http.Response
}

func (o *MoveBattleStyleReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveBattleStyleReadResponse) GetMoveBattleStyle() *shared.MoveBattleStyle {
	if o == nil {
		return nil
	}
	return o.MoveBattleStyle
}

func (o *MoveBattleStyleReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveBattleStyleReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
