// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// MoveList200ApplicationJSON - OK
type MoveList200ApplicationJSON struct {
	// The total number of moves.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of moves.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of moves.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Move `json:"results,omitempty"`
}

type MoveListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	MoveList200ApplicationJSONObject *MoveList200ApplicationJSON
}
