// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveLearnMethodReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveLearnMethodReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveLearnMethodReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	MoveLearnMethod *shared.MoveLearnMethod
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *MoveLearnMethodReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveLearnMethodReadResponse) GetMoveLearnMethod() *shared.MoveLearnMethod {
	if o == nil {
		return nil
	}
	return o.MoveLearnMethod
}

func (o *MoveLearnMethodReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveLearnMethodReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
