// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type MoveAilmentReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *MoveAilmentReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type MoveAilmentReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	MoveAilment *shared.MoveAilment
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *MoveAilmentReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *MoveAilmentReadResponse) GetMoveAilment() *shared.MoveAilment {
	if o == nil {
		return nil
	}
	return o.MoveAilment
}

func (o *MoveAilmentReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *MoveAilmentReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
