// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type NatureListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *NatureListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *NatureListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// NatureListResponseBody - OK
type NatureListResponseBody struct {
	// The total number of natures.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of natures.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of natures.
	Previous *string         `json:"previous,omitempty"`
	Results  []shared.Nature `json:"results,omitempty"`
}

func (o *NatureListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *NatureListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *NatureListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *NatureListResponseBody) GetResults() []shared.Nature {
	if o == nil {
		return nil
	}
	return o.Results
}

type NatureListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *NatureListResponseBody
}

func (o *NatureListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *NatureListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *NatureListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *NatureListResponse) GetObject() *NatureListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
