// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type NatureListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// NatureList200ApplicationJSON - OK
type NatureList200ApplicationJSON struct {
	// The total number of natures.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of natures.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of natures.
	Previous *string         `json:"previous,omitempty"`
	Results  []shared.Nature `json:"results,omitempty"`
}

type NatureListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	NatureList200ApplicationJSONObject *NatureList200ApplicationJSON
}
