// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type NatureReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type NatureReadResponse struct {
	ContentType string
	// Successful response
	Nature      *shared.Nature
	StatusCode  int
	RawResponse *http.Response
}
