// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PalParkAreaReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type PalParkAreaReadResponse struct {
	ContentType string
	// Successful response
	PalParkArea *shared.PalParkArea
	StatusCode  int
	RawResponse *http.Response
}
