// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PalParkAreaListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// PalParkAreaList200ApplicationJSON - OK
type PalParkAreaList200ApplicationJSON struct {
	// The total number of pal park areas.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pal park areas.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pal park areas.
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.PalParkArea `json:"results,omitempty"`
}

type PalParkAreaListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PalParkAreaList200ApplicationJSONObject *PalParkAreaList200ApplicationJSON
}
