// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PalParkAreaListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PalParkAreaListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PalParkAreaListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PalParkAreaList200ApplicationJSON - OK
type PalParkAreaList200ApplicationJSON struct {
	// The total number of pal park areas.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pal park areas.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pal park areas.
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.PalParkArea `json:"results,omitempty"`
}

func (o *PalParkAreaList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PalParkAreaList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PalParkAreaList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PalParkAreaList200ApplicationJSON) GetResults() []shared.PalParkArea {
	if o == nil {
		return nil
	}
	return o.Results
}

type PalParkAreaListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PalParkAreaList200ApplicationJSONObject *PalParkAreaList200ApplicationJSON
}

func (o *PalParkAreaListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PalParkAreaListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PalParkAreaListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PalParkAreaListResponse) GetPalParkAreaList200ApplicationJSONObject() *PalParkAreaList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PalParkAreaList200ApplicationJSONObject
}
