// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PalParkAreaReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PalParkAreaReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PalParkAreaReadResponse struct {
	ContentType string
	// Successful response
	PalParkArea *shared.PalParkArea
	StatusCode  int
	RawResponse *http.Response
}

func (o *PalParkAreaReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PalParkAreaReadResponse) GetPalParkArea() *shared.PalParkArea {
	if o == nil {
		return nil
	}
	return o.PalParkArea
}

func (o *PalParkAreaReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PalParkAreaReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
