// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonHabitatListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonHabitatListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonHabitatListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokemonHabitatList200ApplicationJSON - OK
type PokemonHabitatList200ApplicationJSON struct {
	// The total number of pokemon habitats.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon habitats.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon habitats.
	Previous *string                 `json:"previous,omitempty"`
	Results  []shared.PokemonHabitat `json:"results,omitempty"`
}

func (o *PokemonHabitatList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokemonHabitatList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokemonHabitatList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokemonHabitatList200ApplicationJSON) GetResults() []shared.PokemonHabitat {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokemonHabitatListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PokemonHabitatList200ApplicationJSONObject *PokemonHabitatList200ApplicationJSON
}

func (o *PokemonHabitatListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonHabitatListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonHabitatListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonHabitatListResponse) GetPokemonHabitatList200ApplicationJSONObject() *PokemonHabitatList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PokemonHabitatList200ApplicationJSONObject
}
