// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonColorReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type PokemonColorReadResponse struct {
	ContentType string
	// Successful response
	PokemonColor *shared.PokemonColor
	StatusCode   int
	RawResponse  *http.Response
}
