// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokemonList200ApplicationJSON - OK
type PokemonList200ApplicationJSON struct {
	// The total number of pokemons.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemons.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemons.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Pokemon `json:"results,omitempty"`
}

func (o *PokemonList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokemonList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokemonList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokemonList200ApplicationJSON) GetResults() []shared.Pokemon {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokemonListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonList200ApplicationJSONObject *PokemonList200ApplicationJSON
}

func (o *PokemonListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonListResponse) GetPokemonList200ApplicationJSONObject() *PokemonList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PokemonList200ApplicationJSONObject
}
