// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokedexListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// PokedexList200ApplicationJSON - OK
type PokedexList200ApplicationJSON struct {
	// The total number of pokedexes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokedexes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokedexes.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Pokedex `json:"results,omitempty"`
}

type PokedexListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokedexList200ApplicationJSONObject *PokedexList200ApplicationJSON
}
