// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokedexReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type PokedexReadResponse struct {
	ContentType string
	// Successful response
	Pokedex     *shared.Pokedex
	StatusCode  int
	RawResponse *http.Response
}
