// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonSpeciesListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonSpeciesListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonSpeciesListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokemonSpeciesList200ApplicationJSON - OK
type PokemonSpeciesList200ApplicationJSON struct {
	// The total number of pokemon species list.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon species list.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon species list.
	Previous *string                 `json:"previous,omitempty"`
	Results  []shared.PokemonSpecies `json:"results,omitempty"`
}

func (o *PokemonSpeciesList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokemonSpeciesList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokemonSpeciesList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokemonSpeciesList200ApplicationJSON) GetResults() []shared.PokemonSpecies {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokemonSpeciesListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonSpeciesList200ApplicationJSONObject *PokemonSpeciesList200ApplicationJSON
}

func (o *PokemonSpeciesListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonSpeciesListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonSpeciesListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonSpeciesListResponse) GetPokemonSpeciesList200ApplicationJSONObject() *PokemonSpeciesList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PokemonSpeciesList200ApplicationJSONObject
}
