// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonColorListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// PokemonColorList200ApplicationJSON - OK
type PokemonColorList200ApplicationJSON struct {
	// The total number of pokemon colors.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon colors.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon colors.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.PokemonColor `json:"results,omitempty"`
}

type PokemonColorListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonColorList200ApplicationJSONObject *PokemonColorList200ApplicationJSON
}
