// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonShapeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonShapeListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonShapeListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokemonShapeList200ApplicationJSON - OK
type PokemonShapeList200ApplicationJSON struct {
	// The total number of pokemon shapes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon shapes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon shapes.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.PokemonShape `json:"results,omitempty"`
}

func (o *PokemonShapeList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokemonShapeList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokemonShapeList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokemonShapeList200ApplicationJSON) GetResults() []shared.PokemonShape {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokemonShapeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonShapeList200ApplicationJSONObject *PokemonShapeList200ApplicationJSON
}

func (o *PokemonShapeListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonShapeListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonShapeListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonShapeListResponse) GetPokemonShapeList200ApplicationJSONObject() *PokemonShapeList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PokemonShapeList200ApplicationJSONObject
}
