// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonShapeReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type PokemonShapeReadResponse struct {
	ContentType string
	// Successful response
	PokemonShape *shared.PokemonShape
	StatusCode   int
	RawResponse  *http.Response
}
