// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokedexListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokedexListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokedexListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokedexList200ApplicationJSON - OK
type PokedexList200ApplicationJSON struct {
	// The total number of pokedexes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokedexes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokedexes.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Pokedex `json:"results,omitempty"`
}

func (o *PokedexList200ApplicationJSON) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokedexList200ApplicationJSON) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokedexList200ApplicationJSON) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokedexList200ApplicationJSON) GetResults() []shared.Pokedex {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokedexListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	PokedexList200ApplicationJSONObject *PokedexList200ApplicationJSON
}

func (o *PokedexListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokedexListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokedexListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokedexListResponse) GetPokedexList200ApplicationJSONObject() *PokedexList200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.PokedexList200ApplicationJSONObject
}
