// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokedexReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PokedexReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PokedexReadResponse struct {
	ContentType string
	// Successful response
	Pokedex     *shared.Pokedex
	StatusCode  int
	RawResponse *http.Response
}

func (o *PokedexReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokedexReadResponse) GetPokedex() *shared.Pokedex {
	if o == nil {
		return nil
	}
	return o.Pokedex
}

func (o *PokedexReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokedexReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
