// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonShapeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// PokemonShapeList200ApplicationJSON - OK
type PokemonShapeList200ApplicationJSON struct {
	// The total number of pokemon shapes.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon shapes.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon shapes.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.PokemonShape `json:"results,omitempty"`
}

type PokemonShapeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonShapeList200ApplicationJSONObject *PokemonShapeList200ApplicationJSON
}
