// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonHabitatReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type PokemonHabitatReadResponse struct {
	ContentType string
	// Successful response
	PokemonHabitat *shared.PokemonHabitat
	StatusCode     int
	RawResponse    *http.Response
}
