// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// PokemonList200ApplicationJSON - OK
type PokemonList200ApplicationJSON struct {
	// The total number of pokemons.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemons.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemons.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Pokemon `json:"results,omitempty"`
}

type PokemonListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PokemonList200ApplicationJSONObject *PokemonList200ApplicationJSON
}
