// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokemonFormListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *PokemonFormListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PokemonFormListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// PokemonFormListResponseBody - OK
type PokemonFormListResponseBody struct {
	// The total number of pokemon forms.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of pokemon forms.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of pokemon forms.
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.PokemonForm `json:"results,omitempty"`
}

func (o *PokemonFormListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *PokemonFormListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *PokemonFormListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *PokemonFormListResponseBody) GetResults() []shared.PokemonForm {
	if o == nil {
		return nil
	}
	return o.Results
}

type PokemonFormListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *PokemonFormListResponseBody
}

func (o *PokemonFormListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokemonFormListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokemonFormListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PokemonFormListResponse) GetObject() *PokemonFormListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
