// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type PokeathlonStatReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PokeathlonStatReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type PokeathlonStatReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful response
	PokeathlonStat *shared.PokeathlonStat
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PokeathlonStatReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PokeathlonStatReadResponse) GetPokeathlonStat() *shared.PokeathlonStat {
	if o == nil {
		return nil
	}
	return o.PokeathlonStat
}

func (o *PokeathlonStatReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PokeathlonStatReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
