// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type RegionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *RegionListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *RegionListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// RegionListResponseBody - OK
type RegionListResponseBody struct {
	// The total number of regions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of regions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of regions.
	Previous *string         `json:"previous,omitempty"`
	Results  []shared.Region `json:"results,omitempty"`
}

func (o *RegionListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *RegionListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *RegionListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *RegionListResponseBody) GetResults() []shared.Region {
	if o == nil {
		return nil
	}
	return o.Results
}

type RegionListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *RegionListResponseBody
}

func (o *RegionListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RegionListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RegionListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RegionListResponse) GetObject() *RegionListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
