// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type RegionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// RegionList200ApplicationJSON - OK
type RegionList200ApplicationJSON struct {
	// The total number of regions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of regions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of regions.
	Previous *string         `json:"previous,omitempty"`
	Results  []shared.Region `json:"results,omitempty"`
}

type RegionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	RegionList200ApplicationJSONObject *RegionList200ApplicationJSON
}
