// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type StatListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// StatList200ApplicationJSON - OK
type StatList200ApplicationJSON struct {
	// The total number of stats.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of stats.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of stats.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Stat `json:"results,omitempty"`
}

type StatListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	StatList200ApplicationJSONObject *StatList200ApplicationJSON
}
