// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type StatReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *StatReadRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type StatReadResponse struct {
	ContentType string
	// Successful response
	Stat        *shared.Stat
	StatusCode  int
	RawResponse *http.Response
}

func (o *StatReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *StatReadResponse) GetStat() *shared.Stat {
	if o == nil {
		return nil
	}
	return o.Stat
}

func (o *StatReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *StatReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
