// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type TypeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *TypeListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *TypeListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// TypeListResponseBody - OK
type TypeListResponseBody struct {
	// The total number of types.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of types.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of types.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Type `json:"results,omitempty"`
}

func (o *TypeListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *TypeListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *TypeListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *TypeListResponseBody) GetResults() []shared.Type {
	if o == nil {
		return nil
	}
	return o.Results
}

type TypeListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *TypeListResponseBody
}

func (o *TypeListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TypeListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TypeListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TypeListResponse) GetObject() *TypeListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
