// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type TypeListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// TypeList200ApplicationJSON - OK
type TypeList200ApplicationJSON struct {
	// The total number of types.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of types.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of types.
	Previous *string       `json:"previous,omitempty"`
	Results  []shared.Type `json:"results,omitempty"`
}

type TypeListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	TypeList200ApplicationJSONObject *TypeList200ApplicationJSON
}
