// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type VersionGroupReadRequest struct {
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

type VersionGroupReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful response
	VersionGroup *shared.VersionGroup
}
