// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type VersionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

func (o *VersionListRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *VersionListRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

// VersionListResponseBody - OK
type VersionListResponseBody struct {
	// The total number of versions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of versions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of versions.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Version `json:"results,omitempty"`
}

func (o *VersionListResponseBody) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *VersionListResponseBody) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *VersionListResponseBody) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *VersionListResponseBody) GetResults() []shared.Version {
	if o == nil {
		return nil
	}
	return o.Results
}

type VersionListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *VersionListResponseBody
}

func (o *VersionListResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *VersionListResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *VersionListResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *VersionListResponse) GetObject() *VersionListResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
