// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type VersionGroupListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// VersionGroupList200ApplicationJSON - OK
type VersionGroupList200ApplicationJSON struct {
	// The total number of version groups.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of version groups.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of version groups.
	Previous *string               `json:"previous,omitempty"`
	Results  []shared.VersionGroup `json:"results,omitempty"`
}

type VersionGroupListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	VersionGroupList200ApplicationJSONObject *VersionGroupList200ApplicationJSON
}
