// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"homework/pkg/models/shared"
	"net/http"
)

type VersionListRequest struct {
	Limit  *int64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

// VersionList200ApplicationJSON - OK
type VersionList200ApplicationJSON struct {
	// The total number of versions.
	Count *int64 `json:"count,omitempty"`
	// URL to retrieve the next page of versions.
	Next *string `json:"next,omitempty"`
	// URL to retrieve the previous page of versions.
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Version `json:"results,omitempty"`
}

type VersionListResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	VersionList200ApplicationJSONObject *VersionList200ApplicationJSON
}
