// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AbilityGeneration struct {
	// The generation this ability originated in.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for this generation.
	URL *string `json:"url,omitempty"`
}

func (o *AbilityGeneration) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AbilityGeneration) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type AbilityNamesLanguage struct {
	// The name of the language.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the language.
	URL *string `json:"url,omitempty"`
}

func (o *AbilityNamesLanguage) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AbilityNamesLanguage) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type AbilityNames struct {
	Language *AbilityNamesLanguage `json:"language,omitempty"`
	// The localized name for an API resource in a specific language.
	Name *string `json:"name,omitempty"`
}

func (o *AbilityNames) GetLanguage() *AbilityNamesLanguage {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *AbilityNames) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// Ability - Successful response
type Ability struct {
	Generation *AbilityGeneration `json:"generation,omitempty"`
	// The identifier for this ability resource.
	ID *int `json:"id,omitempty"`
	// Whether or not this ability originated in the main series of the video games.
	IsMainSeries *bool `json:"is_main_series,omitempty"`
	// The name for this ability resource.
	Name  *string        `json:"name,omitempty"`
	Names []AbilityNames `json:"names,omitempty"`
}

func (o *Ability) GetGeneration() *AbilityGeneration {
	if o == nil {
		return nil
	}
	return o.Generation
}

func (o *Ability) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Ability) GetIsMainSeries() *bool {
	if o == nil {
		return nil
	}
	return o.IsMainSeries
}

func (o *Ability) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Ability) GetNames() []AbilityNames {
	if o == nil {
		return nil
	}
	return o.Names
}
