// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AbilityEffectChange struct {
	EffectEntries []Effect         `json:"effect_entries"`
	VersionGroup  NamedAPIResource `json:"version_group"`
}

func (o *AbilityEffectChange) GetEffectEntries() []Effect {
	if o == nil {
		return []Effect{}
	}
	return o.EffectEntries
}

func (o *AbilityEffectChange) GetVersionGroup() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.VersionGroup
}
