// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AbilityEffectChange struct {
	EffectEntries []Effect         `json:"effect_entries"`
	VersionGroup  NamedAPIResource `json:"version_group"`
}
