// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type APIResource struct {
	// The ID of the referenced resource.
	ID *int `json:"id,omitempty"`
	// The name of the referenced resource.
	Name *string `json:"name,omitempty"`
	// The URL of the referenced resource.
	URL *string `json:"url,omitempty"`
}
