// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BerryFirmnessBerries struct {
}

// BerryFirmness - Successful response
type BerryFirmness struct {
	Berries []BerryFirmnessBerries `json:"berries,omitempty"`
	// The identifier for this berry firmness resource
	ID int64 `json:"id"`
	// The name for this berry firmness resource
	Name string `json:"name"`
}
