// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BerryFlavor struct {
	// A list of the berries with this flavor
	Berries []BerryFlavorMap `json:"berries,omitempty"`
	// The identifier for this berry flavor resource
	ID int64 `json:"id"`
	// The name for this berry flavor resource
	Name string `json:"name"`
}

func (o *BerryFlavor) GetBerries() []BerryFlavorMap {
	if o == nil {
		return nil
	}
	return o.Berries
}

func (o *BerryFlavor) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *BerryFlavor) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
