// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BerryFlavorMapBerry struct {
}

type BerryFlavorMap struct {
	Berry BerryFlavorMapBerry `json:"berry"`
	// How powerful the referenced flavor is for this berry
	Potency int64 `json:"potency"`
}

func (o *BerryFlavorMap) GetBerry() BerryFlavorMapBerry {
	if o == nil {
		return BerryFlavorMapBerry{}
	}
	return o.Berry
}

func (o *BerryFlavorMap) GetPotency() int64 {
	if o == nil {
		return 0
	}
	return o.Potency
}
