// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BerryFlavor - Successful response
type BerryFlavor struct {
	// A list of the berries with this flavor
	Berries []BerryFlavorMap `json:"berries,omitempty"`
	// The identifier for this berry flavor resource
	ID int64 `json:"id"`
	// The name for this berry flavor resource
	Name string `json:"name"`
}
