// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BerryFirmnessBerries struct {
}

type BerryFirmness struct {
	Berries []BerryFirmnessBerries `json:"berries,omitempty"`
	// The identifier for this berry firmness resource
	ID int64 `json:"id"`
	// The name for this berry firmness resource
	Name string `json:"name"`
}

func (o *BerryFirmness) GetBerries() []BerryFirmnessBerries {
	if o == nil {
		return nil
	}
	return o.Berries
}

func (o *BerryFirmness) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *BerryFirmness) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
