// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Berry - Successful response
type Berry struct {
	Firmness BerryFirmness `json:"firmness"`
	// A list of references to each flavor a berry can have and the potency of each of those flavors in regard to this berry.
	Flavors []BerryFlavorMap `json:"flavors"`
	// Time it takes the tree to grow one stage, in hours. Berry trees go through four of these growth stages before they can be picked.
	GrowthTime int64 `json:"growth_time"`
	// The identifier for this berry resource
	ID int64 `json:"id"`
	// The maximum number of these berries that can grow on one tree in Generation IV
	MaxHarvest int64 `json:"max_harvest"`
	// The name for this berry resource
	Name string `json:"name"`
	// The power of the move "Natural Gift" when used with this Berry
	NaturalGiftPower int64 `json:"natural_gift_power"`
	// The size of this Berry, in millimeters
	Size int64 `json:"size"`
	// The smoothness of this Berry, used in making Pokéblocks or Poffins
	Smoothness int64 `json:"smoothness"`
	// The speed at which this Berry dries out the soil as it grows. A higher rate means the soil dries more quickly.
	SoilDryness int64 `json:"soil_dryness"`
}
