// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BerryFlavorMapBerry struct {
}

type BerryFlavorMap struct {
	Berry BerryFlavorMapBerry `json:"berry"`
	// How powerful the referenced flavor is for this berry
	Potency int64 `json:"potency"`
}
