// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContestComboSets struct {
	Normal *ContestComboDetail `json:"normal,omitempty"`
	Super  *ContestComboDetail `json:"super,omitempty"`
}

func (o *ContestComboSets) GetNormal() *ContestComboDetail {
	if o == nil {
		return nil
	}
	return o.Normal
}

func (o *ContestComboSets) GetSuper() *ContestComboDetail {
	if o == nil {
		return nil
	}
	return o.Super
}
