// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContestType - Successful response
type ContestType struct {
	BerryFlavor BerryFlavor `json:"berry_flavor"`
	// The identifier for this contest type resource
	ID int64 `json:"id"`
	// The name for this contest type resource
	Name string `json:"name"`
	// The name of this contest type listed in different languages
	Names []ContestName `json:"names"`
}
