// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Description struct {
	Description *string   `json:"description,omitempty"`
	Language    *Language `json:"language,omitempty"`
}
