// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EffectContestCombos - A detail of combos this move can be used in
type EffectContestCombos struct {
}

type EffectEffectChanges struct {
}

// Effect - An effect that occurs in a game, e.g. causing a Pokémon to fall asleep.
type Effect struct {
	// A detail of combos this move can be used in
	ContestCombos *EffectContestCombos `json:"contest_combos,omitempty"`
	ContestType   *ContestType         `json:"contest_type,omitempty"`
	// The chance of this move having an additional effect listed in percentage
	EffectChance *int64 `json:"effect_chance,omitempty"`
	// The list of effects that are changed by this ability
	EffectChanges []EffectEffectChanges `json:"effect_changes,omitempty"`
	// The list of effect text entries
	EffectEntries []EffectEffect `json:"effect_entries,omitempty"`
	// The flavor text entries that describe this effect
	FlavorTextEntries []FlavorText `json:"flavor_text_entries,omitempty"`
	Generation        *Generation  `json:"generation,omitempty"`
	// The identifier for this effect resource
	ID *int64 `json:"id,omitempty"`
	// The machines that teach this move
	Machines []MachineVersionDetail `json:"machines,omitempty"`
	Meta     *MoveMetaData          `json:"meta,omitempty"`
	// The name for this effect resource
	Name *string `json:"name,omitempty"`
	// The flavor text entries that describe this effect
	PokemonFlavorTextEntries []EffectEffect `json:"pokemon_flavor_text_entries,omitempty"`
	// The short description of this effect listed in different languages
	ShortEffect *string `json:"short_effect,omitempty"`
	// The list of stat changes that are caused by this effect
	StatChanges        []MoveStatChange    `json:"stat_changes,omitempty"`
	SuperContestEffect *SuperContestEffect `json:"super_contest_effect,omitempty"`
	TargetSpecies      *PokemonSpecies     `json:"target_species,omitempty"`
}
