// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EffectEffect - The various effects of the move `effect_entries`
type EffectEffect struct {
	// The localized effect text of this effect
	Effect   string   `json:"effect"`
	Language Language `json:"language"`
}

func (o *EffectEffect) GetEffect() string {
	if o == nil {
		return ""
	}
	return o.Effect
}

func (o *EffectEffect) GetLanguage() Language {
	if o == nil {
		return Language{}
	}
	return o.Language
}
