// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EggGroup - Successful response
type EggGroup struct {
	// The identifier for this egg group resource
	ID int64 `json:"id"`
	// The name for this egg group resource
	Name string `json:"name"`
	// The name of this egg group listed in different languages
	Names []Name `json:"names"`
	// A list of all Pokemon species that are members of this egg group
	PokemonSpecies []NamedAPIResource `json:"pokemon_species"`
}

func (o *EggGroup) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *EggGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EggGroup) GetNames() []Name {
	if o == nil {
		return []Name{}
	}
	return o.Names
}

func (o *EggGroup) GetPokemonSpecies() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.PokemonSpecies
}
