// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EncounterCondition - Successful response
type EncounterCondition struct {
	// The identifier for this encounter condition resource
	ID int64 `json:"id"`
	// The name for this encounter condition resource
	Name string `json:"name"`
	// The name of this encounter condition listed in different languages
	Names []Name `json:"names"`
	// A list of values that are used with this encounter condition
	Values []NamedAPIResource `json:"values"`
}
