// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EncounterMethodRate struct {
	EncounterMethod *EncounterMethod          `json:"encounter_method,omitempty"`
	VersionDetails  []EncounterVersionDetails `json:"version_details,omitempty"`
}

func (o *EncounterMethodRate) GetEncounterMethod() *EncounterMethod {
	if o == nil {
		return nil
	}
	return o.EncounterMethod
}

func (o *EncounterMethodRate) GetVersionDetails() []EncounterVersionDetails {
	if o == nil {
		return nil
	}
	return o.VersionDetails
}
