// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Encounter struct {
	// Percent chance that this encounter will occur.
	Chance *int64 `json:"chance,omitempty"`
	// The condition which triggers this encounter.
	ConditionValues []EncounterConditionValue `json:"condition_values,omitempty"`
	// The highest level the Pokémon could be encountered at.
	MaxLevel int64           `json:"max_level"`
	Method   EncounterMethod `json:"method"`
	// The lowest level the Pokémon could be encountered at.
	MinLevel int64 `json:"min_level"`
}
