// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EncounterCondition - Successful response
type EncounterCondition struct {
	// The identifier for this encounter condition resource
	ID int64 `json:"id"`
	// The name for this encounter condition resource
	Name string `json:"name"`
	// The name of this encounter condition listed in different languages
	Names []Name `json:"names"`
	// A list of values that are used with this encounter condition
	Values []NamedAPIResource `json:"values"`
}

func (o *EncounterCondition) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *EncounterCondition) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EncounterCondition) GetNames() []Name {
	if o == nil {
		return []Name{}
	}
	return o.Names
}

func (o *EncounterCondition) GetValues() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.Values
}
