// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EncounterConditionValue struct {
	Condition NamedAPIResource `json:"condition"`
	// The identifier for this encounter condition value resource
	ID int64 `json:"id"`
	// The name for this encounter condition value resource
	Name string `json:"name"`
	// The name of this encounter condition value listed in different languages
	Names []Name `json:"names"`
}

func (o *EncounterConditionValue) GetCondition() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.Condition
}

func (o *EncounterConditionValue) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *EncounterConditionValue) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EncounterConditionValue) GetNames() []Name {
	if o == nil {
		return []Name{}
	}
	return o.Names
}
