// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EncounterMethod struct {
	// The identifier for this encounter method resource
	ID int64 `json:"id"`
	// The name for this encounter method resource
	Name string `json:"name"`
	// A good value for sorting
	Order int64 `json:"order"`
}

func (o *EncounterMethod) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *EncounterMethod) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *EncounterMethod) GetOrder() int64 {
	if o == nil {
		return 0
	}
	return o.Order
}
