// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EvolutionTrigger - Successful response
type EvolutionTrigger struct {
	// The identifier for this evolution trigger resource
	ID *int64 `json:"id,omitempty"`
	// The name for this evolution trigger resource
	Name *string `json:"name,omitempty"`
}

func (o *EvolutionTrigger) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *EvolutionTrigger) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
