// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FlavorText struct {
	FlavorText *string           `json:"flavor_text,omitempty"`
	Language   *NamedAPIResource `json:"language,omitempty"`
	Version    *NamedAPIResource `json:"version,omitempty"`
}
