// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenderPokemonSpeciesDetails struct {
	// The chance of this Pokémon being female, in eighths; or -1 for genderless
	Rate *int64 `json:"rate,omitempty"`
}

// Gender - Successful response
type Gender struct {
	// The identifier for this gender resource
	ID *int64 `json:"id,omitempty"`
	// The name for this gender resource
	Name                  *string                       `json:"name,omitempty"`
	PokemonSpeciesDetails []GenderPokemonSpeciesDetails `json:"pokemon_species_details,omitempty"`
}
