// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Abilities struct {
	// Whether or not this ability is a hidden one
	IsHidden *bool `json:"is_hidden,omitempty"`
	// The name of this ability
	Name *string `json:"name,omitempty"`
	// The slot this ability occupies in this Pokémon species
	Slot *int64 `json:"slot,omitempty"`
}

func (o *Abilities) GetIsHidden() *bool {
	if o == nil {
		return nil
	}
	return o.IsHidden
}

func (o *Abilities) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Abilities) GetSlot() *int64 {
	if o == nil {
		return nil
	}
	return o.Slot
}

type GenerationNames struct {
	Language *Language `json:"language,omitempty"`
	// The localized name for an API resource in a specific language
	Name *string `json:"name,omitempty"`
}

func (o *GenerationNames) GetLanguage() *Language {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *GenerationNames) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type Generation struct {
	Abilities []Abilities `json:"abilities,omitempty"`
	// The identifier for this generation resource
	ID *int64 `json:"id,omitempty"`
	// The name for this generation resource
	Name  *string           `json:"name,omitempty"`
	Names []GenerationNames `json:"names,omitempty"`
}

func (o *Generation) GetAbilities() []Abilities {
	if o == nil {
		return nil
	}
	return o.Abilities
}

func (o *Generation) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Generation) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Generation) GetNames() []GenerationNames {
	if o == nil {
		return nil
	}
	return o.Names
}
