// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GenerationGameIndex struct {
	// The internal id of an API resource within game data.
	GameIndex  *int        `json:"game_index,omitempty"`
	Generation *Generation `json:"generation,omitempty"`
}
