// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Genus struct {
	Genus    *string   `json:"genus,omitempty"`
	Language *Language `json:"language,omitempty"`
}

func (o *Genus) GetGenus() *string {
	if o == nil {
		return nil
	}
	return o.Genus
}

func (o *Genus) GetLanguage() *Language {
	if o == nil {
		return nil
	}
	return o.Language
}
