// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Genus struct {
	Genus    *string   `json:"genus,omitempty"`
	Language *Language `json:"language,omitempty"`
}
