// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GrowthRate - Successful response
type GrowthRate struct {
	// The description of this growth rate listed in different languages
	Descriptions []Description `json:"descriptions,omitempty"`
	// The formula used to calculate the rate at which the Pokémon species gains level
	Formula *string `json:"formula,omitempty"`
	// The identifier for this growth rate resource
	ID *int64 `json:"id,omitempty"`
	// The name for this growth rate resource
	Name *string `json:"name,omitempty"`
}

func (o *GrowthRate) GetDescriptions() []Description {
	if o == nil {
		return nil
	}
	return o.Descriptions
}

func (o *GrowthRate) GetFormula() *string {
	if o == nil {
		return nil
	}
	return o.Formula
}

func (o *GrowthRate) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GrowthRate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
