// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ItemCategory - Successful response
type ItemCategory struct {
	// The identifier for this item category resource
	ID *int64 `json:"id,omitempty"`
	// A list of items that are a part of this category
	Items []NamedAPIResource `json:"items,omitempty"`
	// The name for this item category resource
	Name *string `json:"name,omitempty"`
}
