// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ItemAttribute - Successful response
type ItemAttribute struct {
	// The identifier for this item attribute resource
	ID *int64 `json:"id,omitempty"`
	// A list of items that have this attribute
	Items []NamedAPIResource `json:"items,omitempty"`
	// The name for this item attribute resource
	Name *string `json:"name,omitempty"`
}
