// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Item struct {
	Attributes        []ItemAttribute  `json:"attributes,omitempty"`
	Category          *ItemCategory    `json:"category,omitempty"`
	Cost              *int             `json:"cost,omitempty"`
	EffectEntries     []VerboseEffect  `json:"effect_entries,omitempty"`
	FlavorTextEntries []FlavorText     `json:"flavor_text_entries,omitempty"`
	FlingEffect       *ItemFlingEffect `json:"fling_effect,omitempty"`
	FlingPower        *int             `json:"fling_power,omitempty"`
	ID                *int             `json:"id,omitempty"`
	Name              *string          `json:"name,omitempty"`
}

func (o *Item) GetAttributes() []ItemAttribute {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *Item) GetCategory() *ItemCategory {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *Item) GetCost() *int {
	if o == nil {
		return nil
	}
	return o.Cost
}

func (o *Item) GetEffectEntries() []VerboseEffect {
	if o == nil {
		return nil
	}
	return o.EffectEntries
}

func (o *Item) GetFlavorTextEntries() []FlavorText {
	if o == nil {
		return nil
	}
	return o.FlavorTextEntries
}

func (o *Item) GetFlingEffect() *ItemFlingEffect {
	if o == nil {
		return nil
	}
	return o.FlingEffect
}

func (o *Item) GetFlingPower() *int {
	if o == nil {
		return nil
	}
	return o.FlingPower
}

func (o *Item) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Item) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
