// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Language struct {
	ID       *int    `json:"id,omitempty"`
	Iso3166  *string `json:"iso3166,omitempty"`
	Iso639   *string `json:"iso639,omitempty"`
	Name     *string `json:"name,omitempty"`
	Names    []Name  `json:"names,omitempty"`
	Official *bool   `json:"official,omitempty"`
}

func (o *Language) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Language) GetIso3166() *string {
	if o == nil {
		return nil
	}
	return o.Iso3166
}

func (o *Language) GetIso639() *string {
	if o == nil {
		return nil
	}
	return o.Iso639
}

func (o *Language) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Language) GetNames() []Name {
	if o == nil {
		return nil
	}
	return o.Names
}

func (o *Language) GetOfficial() *bool {
	if o == nil {
		return nil
	}
	return o.Official
}
