// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Language - Successful response
type Language struct {
	ID       *int    `json:"id,omitempty"`
	Iso3166  *string `json:"iso3166,omitempty"`
	Iso639   *string `json:"iso639,omitempty"`
	Name     *string `json:"name,omitempty"`
	Names    []Name  `json:"names,omitempty"`
	Official *bool   `json:"official,omitempty"`
}
