// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Location struct {
	Areas       []NamedAPIResource    `json:"areas,omitempty"`
	GameIndices []GenerationGameIndex `json:"game_indices,omitempty"`
	ID          *int                  `json:"id,omitempty"`
	Name        *string               `json:"name,omitempty"`
	Names       []Name                `json:"names,omitempty"`
	Region      *NamedAPIResource     `json:"region,omitempty"`
}

func (o *Location) GetAreas() []NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Areas
}

func (o *Location) GetGameIndices() []GenerationGameIndex {
	if o == nil {
		return nil
	}
	return o.GameIndices
}

func (o *Location) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Location) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Location) GetNames() []Name {
	if o == nil {
		return nil
	}
	return o.Names
}

func (o *Location) GetRegion() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Region
}
