// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LocationArea - Successful response
type LocationArea struct {
	EncounterMethodRates []EncounterMethodRate `json:"encounter_method_rates,omitempty"`
	GameIndex            *int                  `json:"game_index,omitempty"`
	ID                   *int                  `json:"id,omitempty"`
	Location             *Location             `json:"location,omitempty"`
	Name                 *string               `json:"name,omitempty"`
	Names                []Name                `json:"names,omitempty"`
	PokemonEncounters    []PokemonEncounter    `json:"pokemon_encounters,omitempty"`
}
