// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Location - Successful response
type Location struct {
	Areas       []NamedAPIResource    `json:"areas,omitempty"`
	GameIndices []GenerationGameIndex `json:"game_indices,omitempty"`
	ID          *int                  `json:"id,omitempty"`
	Name        *string               `json:"name,omitempty"`
	Names       []Name                `json:"names,omitempty"`
	Region      *NamedAPIResource     `json:"region,omitempty"`
}
