// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Machine - Successful response
type Machine struct {
	ID           *int              `json:"id,omitempty"`
	Item         *NamedAPIResource `json:"item,omitempty"`
	Move         *NamedAPIResource `json:"move,omitempty"`
	VersionGroup *NamedAPIResource `json:"version_group,omitempty"`
}
