// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Machine - Successful response
type Machine struct {
	ID           *int              `json:"id,omitempty"`
	Item         *NamedAPIResource `json:"item,omitempty"`
	Move         *NamedAPIResource `json:"move,omitempty"`
	VersionGroup *NamedAPIResource `json:"version_group,omitempty"`
}

func (o *Machine) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Machine) GetItem() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Item
}

func (o *Machine) GetMove() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Move
}

func (o *Machine) GetVersionGroup() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.VersionGroup
}
