// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MachineVersionDetail struct {
	Machine      APIResource `json:"machine"`
	VersionGroup APIResource `json:"version_group"`
}
