// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MachineVersionDetail struct {
	Machine      APIResource `json:"machine"`
	VersionGroup APIResource `json:"version_group"`
}

func (o *MachineVersionDetail) GetMachine() APIResource {
	if o == nil {
		return APIResource{}
	}
	return o.Machine
}

func (o *MachineVersionDetail) GetVersionGroup() APIResource {
	if o == nil {
		return APIResource{}
	}
	return o.VersionGroup
}
