// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveTarget1 - Targets moves can be directed at during battle. Targets can be Pokémon, adjacent positions, all opponents, etc.
type MoveTarget1 struct {
	// The description of this move target listed in different languages
	Descriptions []Description `json:"descriptions"`
	// The identifier for this move target resource
	ID int64 `json:"id"`
	// The name for this move target resource
	Name string `json:"name"`
}
