// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveBattleStylePreference struct {
	// Chance of using the move, in percent, if HP is over one half of maximum HP.
	HighHpPreference int64 `json:"high_hp_preference"`
	// Chance of using the move, in percent, if HP is under one half of maximum HP.
	LowHpPreference int64            `json:"low_hp_preference"`
	MoveBattleStyle NamedAPIResource `json:"move_battle_style"`
}

func (o *MoveBattleStylePreference) GetHighHpPreference() int64 {
	if o == nil {
		return 0
	}
	return o.HighHpPreference
}

func (o *MoveBattleStylePreference) GetLowHpPreference() int64 {
	if o == nil {
		return 0
	}
	return o.LowHpPreference
}

func (o *MoveBattleStylePreference) GetMoveBattleStyle() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.MoveBattleStyle
}
