// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveDamageClass struct {
	Descriptions []Description `json:"descriptions"`
	ID           int           `json:"id"`
	Name         string        `json:"name"`
}

func (o *MoveDamageClass) GetDescriptions() []Description {
	if o == nil {
		return []Description{}
	}
	return o.Descriptions
}

func (o *MoveDamageClass) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *MoveDamageClass) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
