// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveBattleStyle - Successful response
type MoveBattleStyle struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
