// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveMetaData struct {
	Ailment NamedAPIResource `json:"ailment"`
	// The chance of the target being inflicted with the status condition ailment.
	AilmentChance *int64           `json:"ailment_chance,omitempty"`
	Category      NamedAPIResource `json:"category"`
	// Critical hit rate bonus.
	CritRate *int64 `json:"crit_rate,omitempty"`
	// The amount of hp gained by the attacking Pokemon when it uses this move.
	Drain *int64 `json:"drain,omitempty"`
	// The chance of the target flinching when hit by this move.
	FlinchChance *int64 `json:"flinch_chance,omitempty"`
	// The amount of hp gained by the target Pokemon when it receives this move.
	Healing *int64 `json:"healing,omitempty"`
	// The maximum number of times this move hits. Null if it always only hits once.
	MaxHits *int64 `json:"max_hits,omitempty"`
	// The maximum number of turns this move continues to take effect. Null if it always only lasts one turn.
	MaxTurns *int64 `json:"max_turns,omitempty"`
	// The minimum number of times this move hits. Null if it always only hits once.
	MinHits *int64 `json:"min_hits,omitempty"`
	// The minimum number of turns this move continues to take effect. Null if it always only lasts one turn.
	MinTurns *int64 `json:"min_turns,omitempty"`
	// The chance of the attacking Pokemon lowering the target's stat.
	StatChance *int64 `json:"stat_chance,omitempty"`
}
