// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveDamageClass1 - Successful response
type MoveDamageClass1 struct {
	Descriptions []Description `json:"descriptions"`
	ID           int           `json:"id"`
	Name         string        `json:"name"`
}
