// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveStatChange struct {
	// The amount of change to the referenced stat.
	Change int64            `json:"change"`
	Stat   NamedAPIResource `json:"stat"`
}

func (o *MoveStatChange) GetChange() int64 {
	if o == nil {
		return 0
	}
	return o.Change
}

func (o *MoveStatChange) GetStat() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.Stat
}
