// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveCategory - Successful response
type MoveCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (o *MoveCategory) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *MoveCategory) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
