// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveAilment struct {
	ID    int64  `json:"id"`
	Moves []Move `json:"moves"`
	Name  string `json:"name"`
}

func (o *MoveAilment) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *MoveAilment) GetMoves() []Move {
	if o == nil {
		return []Move{}
	}
	return o.Moves
}

func (o *MoveAilment) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
