// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveAilment - Successful response
type MoveAilment struct {
	ID    int64  `json:"id"`
	Moves []Move `json:"moves"`
	Name  string `json:"name"`
}
