// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MoveBattleStylePreference struct {
	// Chance of using the move, in percent, if HP is over one half of maximum HP.
	HighHpPreference int64 `json:"high_hp_preference"`
	// Chance of using the move, in percent, if HP is under one half of maximum HP.
	LowHpPreference int64            `json:"low_hp_preference"`
	MoveBattleStyle NamedAPIResource `json:"move_battle_style"`
}
