// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MoveCategory - Successful response
type MoveCategory struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
