// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NamedAPIResource struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

func (o *NamedAPIResource) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *NamedAPIResource) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}
