// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Name struct {
	Language *NamedAPIResource `json:"language,omitempty"`
	Name     *string           `json:"name,omitempty"`
}
