// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NatureStatAffectSets struct {
	Decrease []NatureStatAffect `json:"decrease"`
	Increase []NatureStatAffect `json:"increase"`
}
