// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NatureStatAffectSets struct {
	Decrease []NatureStatAffect `json:"decrease"`
	Increase []NatureStatAffect `json:"increase"`
}

func (o *NatureStatAffectSets) GetDecrease() []NatureStatAffect {
	if o == nil {
		return []NatureStatAffect{}
	}
	return o.Decrease
}

func (o *NatureStatAffectSets) GetIncrease() []NatureStatAffect {
	if o == nil {
		return []NatureStatAffect{}
	}
	return o.Increase
}
