// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type NatureStatChange struct {
	MaxChange      *int64              `json:"max_change,omitempty"`
	PokeathlonStat *PokeathlonStatName `json:"pokeathlon_stat,omitempty"`
}

func (o *NatureStatChange) GetMaxChange() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxChange
}

func (o *NatureStatChange) GetPokeathlonStat() *PokeathlonStatName {
	if o == nil {
		return nil
	}
	return o.PokeathlonStat
}
