// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Nature - Successful response
type Nature struct {
	DecreasedStat              string                      `json:"decreased_stat"`
	HatesFlavor                string                      `json:"hates_flavor"`
	ID                         int64                       `json:"id"`
	IncreasedStat              string                      `json:"increased_stat"`
	LikesFlavor                string                      `json:"likes_flavor"`
	MoveBattleStylePreferences []MoveBattleStylePreference `json:"move_battle_style_preferences,omitempty"`
	Name                       string                      `json:"name"`
	PokeathlonStatChanges      []NatureStatChange          `json:"pokeathlon_stat_changes,omitempty"`
}
