// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PalParkArea struct {
	// The identifier for this pal park area resource
	ID int64 `json:"id"`
	// The name for this pal park area resource
	Name string `json:"name"`
}

func (o *PalParkArea) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PalParkArea) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
