// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PalParkEncounterArea - Areas where the Pokémon species can be encountered in pal park.
type PalParkEncounterArea struct {
	Area *NamedAPIResource `json:"area,omitempty"`
	// The base score given to the player when the referenced Pokemon is caught during a pal park run.
	BaseScore *int64 `json:"base_score,omitempty"`
	// The base rate for encountering the referenced Pokemon in this pal park area.
	Rate *int64 `json:"rate,omitempty"`
}

func (o *PalParkEncounterArea) GetArea() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Area
}

func (o *PalParkEncounterArea) GetBaseScore() *int64 {
	if o == nil {
		return nil
	}
	return o.BaseScore
}

func (o *PalParkEncounterArea) GetRate() *int64 {
	if o == nil {
		return nil
	}
	return o.Rate
}
