// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PalParkArea - Successful response
type PalParkArea struct {
	// The identifier for this pal park area resource
	ID int64 `json:"id"`
	// The name for this pal park area resource
	Name string `json:"name"`
}
