// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PastMoveStatValuesEffectEntries struct {
	Effect       *VerboseEffect    `json:"effect,omitempty"`
	VersionGroup *NamedAPIResource `json:"version_group,omitempty"`
}

type PastMoveStatValues struct {
	// The percent value of how likely this move is to be successful.
	Accuracy int64 `json:"accuracy"`
	// The percent value of effect occurring.
	EffectChance *int64 `json:"effect_chance,omitempty"`
	// The list of previous effects this move has had across version groups.
	EffectEntries []PastMoveStatValuesEffectEntries `json:"effect_entries,omitempty"`
	// The base power of this move with a value of 0 if it does not have a base power.
	Power int64 `json:"power"`
	// The power points this move has left.
	Pp   int64 `json:"pp"`
	Type *Type `json:"type,omitempty"`
}
