// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PokemonHabitat - Successful response
type PokemonHabitat struct {
	// The identifier for this Pokemon habitat resource
	ID *int64 `json:"id,omitempty"`
	// The name for this Pokemon habitat resource
	Name *string `json:"name,omitempty"`
}

func (o *PokemonHabitat) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PokemonHabitat) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
