// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PokemonColor - Successful response
type PokemonColor struct {
	// The identifier for this Pokemon color resource
	ID *int64 `json:"id,omitempty"`
	// The name for this Pokemon color resource
	Name *string `json:"name,omitempty"`
}
