// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonSprites struct {
	// The default depiction of this Pokémon from the back in battle.
	BackDefault *string `json:"back_default,omitempty"`
	// The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
	BackFemale *string `json:"back_female,omitempty"`
	// The shiny depiction of this Pokémon from the back in battle.
	BackShiny *string `json:"back_shiny,omitempty"`
	// The shiny depiction of this Pokémon from the back in battle, for female gendered Pokémon.
	BackShinyFemale *string `json:"back_shiny_female,omitempty"`
	// The default depiction of this Pokémon from the front in battle.
	FrontDefault *string `json:"front_default,omitempty"`
	// The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
	FrontFemale *string `json:"front_female,omitempty"`
	// The shiny depiction of this Pokémon from the front in battle.
	FrontShiny *string `json:"front_shiny,omitempty"`
	// The shiny depiction of this Pokémon from the front in battle, for female gendered Pokémon.
	FrontShinyFemale *string `json:"front_shiny_female,omitempty"`
}
