// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokeathlonStatName struct {
	Name  *string `json:"name,omitempty"`
	Names []Name  `json:"names,omitempty"`
}
