// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokeathlonStatAffect struct {
	// The maximum amount of change to the referenced Pokéathlon stat.
	MaxChange int64  `json:"max_change"`
	Nature    Nature `json:"nature"`
}
