// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PokemonForm - Successful response
type PokemonForm struct {
	// The identifier for this Pokemon form resource
	ID *int64 `json:"id,omitempty"`
	// The name for this Pokemon form resource
	Name *string `json:"name,omitempty"`
}
