// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PokemonColor - Successful response
type PokemonColor struct {
	// The identifier for this Pokemon color resource
	ID *int64 `json:"id,omitempty"`
	// The name for this Pokemon color resource
	Name *string `json:"name,omitempty"`
}

func (o *PokemonColor) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PokemonColor) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
