// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonMoveVersionGroupDetails struct {
	// The minimum level to learn the move
	LevelLearnedAt  int64            `json:"level_learned_at"`
	MoveLearnMethod NamedAPIResource `json:"move_learn_method"`
	VersionGroup    NamedAPIResource `json:"version_group"`
}

func (o *PokemonMoveVersionGroupDetails) GetLevelLearnedAt() int64 {
	if o == nil {
		return 0
	}
	return o.LevelLearnedAt
}

func (o *PokemonMoveVersionGroupDetails) GetMoveLearnMethod() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.MoveLearnMethod
}

func (o *PokemonMoveVersionGroupDetails) GetVersionGroup() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.VersionGroup
}

type PokemonMove struct {
	Move *NamedAPIResource `json:"move,omitempty"`
	// A list of details showing how the Pokémon can learn the move
	//
	VersionGroupDetails []PokemonMoveVersionGroupDetails `json:"version_group_details,omitempty"`
}

func (o *PokemonMove) GetMove() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Move
}

func (o *PokemonMove) GetVersionGroupDetails() []PokemonMoveVersionGroupDetails {
	if o == nil {
		return nil
	}
	return o.VersionGroupDetails
}
