// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Pokemon - Successful response
type Pokemon struct {
	Abilities              []PokemonAbility   `json:"abilities"`
	BaseExperience         int                `json:"base_experience"`
	Forms                  []PokemonForm      `json:"forms"`
	GameIndices            []VersionGameIndex `json:"game_indices"`
	Height                 int                `json:"height"`
	HeldItems              []PokemonHeldItem  `json:"held_items"`
	ID                     int                `json:"id"`
	IsDefault              bool               `json:"is_default"`
	LocationAreaEncounters string             `json:"location_area_encounters"`
	Moves                  []PokemonMove      `json:"moves"`
	Name                   string             `json:"name"`
	Order                  int                `json:"order"`
	Species                NamedAPIResource   `json:"species"`
	Sprites                PokemonSprites     `json:"sprites"`
	Stats                  []PokemonStat      `json:"stats"`
	Types                  []PokemonType      `json:"types"`
	Weight                 int                `json:"weight"`
}
