// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokeathlonStatName struct {
	Name  *string `json:"name,omitempty"`
	Names []Name  `json:"names,omitempty"`
}

func (o *PokeathlonStatName) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PokeathlonStatName) GetNames() []Name {
	if o == nil {
		return nil
	}
	return o.Names
}
