// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonSpeciesEvolutionChain struct {
}

// PokemonSpecies - Successful response
type PokemonSpecies struct {
	BaseHappiness        *int                          `json:"base_happiness,omitempty"`
	CaptureRate          *int                          `json:"capture_rate,omitempty"`
	Color                *PokemonColor                 `json:"color,omitempty"`
	EggGroups            []EggGroup                    `json:"egg_groups,omitempty"`
	EvolutionChain       *PokemonSpeciesEvolutionChain `json:"evolution_chain,omitempty"`
	EvolvesFromSpecies   *PokemonSpecies               `json:"evolves_from_species,omitempty"`
	FlavorTextEntries    []FlavorText                  `json:"flavor_text_entries,omitempty"`
	FormDescriptions     []Description                 `json:"form_descriptions,omitempty"`
	FormsSwitchable      *bool                         `json:"forms_switchable,omitempty"`
	GenderRate           *int                          `json:"gender_rate,omitempty"`
	Genera               []Genus                       `json:"genera,omitempty"`
	Generation           *Generation                   `json:"generation,omitempty"`
	GrowthRate           *GrowthRate                   `json:"growth_rate,omitempty"`
	Habitat              *PokemonHabitat               `json:"habitat,omitempty"`
	HasGenderDifferences *bool                         `json:"has_gender_differences,omitempty"`
	HatchCounter         *int                          `json:"hatch_counter,omitempty"`
	ID                   *int                          `json:"id,omitempty"`
	IsBaby               *bool                         `json:"is_baby,omitempty"`
	Name                 *string                       `json:"name,omitempty"`
	Names                []Name                        `json:"names,omitempty"`
	Order                *int                          `json:"order,omitempty"`
	PalParkEncounters    []PalParkEncounterArea        `json:"pal_park_encounters,omitempty"`
	PokedexNumbers       []PokemonSpeciesDexEntry      `json:"pokedex_numbers,omitempty"`
	Shape                *PokemonShape                 `json:"shape,omitempty"`
	Varieties            []PokemonSpeciesVariety       `json:"varieties,omitempty"`
}

func (o *PokemonSpecies) GetBaseHappiness() *int {
	if o == nil {
		return nil
	}
	return o.BaseHappiness
}

func (o *PokemonSpecies) GetCaptureRate() *int {
	if o == nil {
		return nil
	}
	return o.CaptureRate
}

func (o *PokemonSpecies) GetColor() *PokemonColor {
	if o == nil {
		return nil
	}
	return o.Color
}

func (o *PokemonSpecies) GetEggGroups() []EggGroup {
	if o == nil {
		return nil
	}
	return o.EggGroups
}

func (o *PokemonSpecies) GetEvolutionChain() *PokemonSpeciesEvolutionChain {
	if o == nil {
		return nil
	}
	return o.EvolutionChain
}

func (o *PokemonSpecies) GetEvolvesFromSpecies() *PokemonSpecies {
	if o == nil {
		return nil
	}
	return o.EvolvesFromSpecies
}

func (o *PokemonSpecies) GetFlavorTextEntries() []FlavorText {
	if o == nil {
		return nil
	}
	return o.FlavorTextEntries
}

func (o *PokemonSpecies) GetFormDescriptions() []Description {
	if o == nil {
		return nil
	}
	return o.FormDescriptions
}

func (o *PokemonSpecies) GetFormsSwitchable() *bool {
	if o == nil {
		return nil
	}
	return o.FormsSwitchable
}

func (o *PokemonSpecies) GetGenderRate() *int {
	if o == nil {
		return nil
	}
	return o.GenderRate
}

func (o *PokemonSpecies) GetGenera() []Genus {
	if o == nil {
		return nil
	}
	return o.Genera
}

func (o *PokemonSpecies) GetGeneration() *Generation {
	if o == nil {
		return nil
	}
	return o.Generation
}

func (o *PokemonSpecies) GetGrowthRate() *GrowthRate {
	if o == nil {
		return nil
	}
	return o.GrowthRate
}

func (o *PokemonSpecies) GetHabitat() *PokemonHabitat {
	if o == nil {
		return nil
	}
	return o.Habitat
}

func (o *PokemonSpecies) GetHasGenderDifferences() *bool {
	if o == nil {
		return nil
	}
	return o.HasGenderDifferences
}

func (o *PokemonSpecies) GetHatchCounter() *int {
	if o == nil {
		return nil
	}
	return o.HatchCounter
}

func (o *PokemonSpecies) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PokemonSpecies) GetIsBaby() *bool {
	if o == nil {
		return nil
	}
	return o.IsBaby
}

func (o *PokemonSpecies) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PokemonSpecies) GetNames() []Name {
	if o == nil {
		return nil
	}
	return o.Names
}

func (o *PokemonSpecies) GetOrder() *int {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *PokemonSpecies) GetPalParkEncounters() []PalParkEncounterArea {
	if o == nil {
		return nil
	}
	return o.PalParkEncounters
}

func (o *PokemonSpecies) GetPokedexNumbers() []PokemonSpeciesDexEntry {
	if o == nil {
		return nil
	}
	return o.PokedexNumbers
}

func (o *PokemonSpecies) GetShape() *PokemonShape {
	if o == nil {
		return nil
	}
	return o.Shape
}

func (o *PokemonSpecies) GetVarieties() []PokemonSpeciesVariety {
	if o == nil {
		return nil
	}
	return o.Varieties
}
