// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonMoveVersionGroupDetails struct {
	// The minimum level to learn the move
	LevelLearnedAt  int64            `json:"level_learned_at"`
	MoveLearnMethod NamedAPIResource `json:"move_learn_method"`
	VersionGroup    NamedAPIResource `json:"version_group"`
}

type PokemonMove struct {
	Move *NamedAPIResource `json:"move,omitempty"`
	// A list of details showing how the Pokémon can learn the move
	//
	VersionGroupDetails []PokemonMoveVersionGroupDetails `json:"version_group_details,omitempty"`
}
