// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonHeldItemVersionDetails struct {
	Rarity  *int64   `json:"rarity,omitempty"`
	Version *Version `json:"version,omitempty"`
}

type PokemonHeldItem struct {
	Item           *Item                           `json:"item,omitempty"`
	VersionDetails []PokemonHeldItemVersionDetails `json:"version_details,omitempty"`
}
