// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonHeldItemVersionDetails struct {
	Rarity  *int64   `json:"rarity,omitempty"`
	Version *Version `json:"version,omitempty"`
}

func (o *PokemonHeldItemVersionDetails) GetRarity() *int64 {
	if o == nil {
		return nil
	}
	return o.Rarity
}

func (o *PokemonHeldItemVersionDetails) GetVersion() *Version {
	if o == nil {
		return nil
	}
	return o.Version
}

type PokemonHeldItem struct {
	Item           *Item                           `json:"item,omitempty"`
	VersionDetails []PokemonHeldItemVersionDetails `json:"version_details,omitempty"`
}

func (o *PokemonHeldItem) GetItem() *Item {
	if o == nil {
		return nil
	}
	return o.Item
}

func (o *PokemonHeldItem) GetVersionDetails() []PokemonHeldItemVersionDetails {
	if o == nil {
		return nil
	}
	return o.VersionDetails
}
