// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Pokedex struct {
	Descriptions   []Description    `json:"descriptions"`
	ID             int64            `json:"id"`
	IsMainSeries   bool             `json:"is_main_series"`
	Name           string           `json:"name"`
	PokemonEntries []PokemonEntry   `json:"pokemon_entries"`
	Region         NamedAPIResource `json:"region"`
}

func (o *Pokedex) GetDescriptions() []Description {
	if o == nil {
		return []Description{}
	}
	return o.Descriptions
}

func (o *Pokedex) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Pokedex) GetIsMainSeries() bool {
	if o == nil {
		return false
	}
	return o.IsMainSeries
}

func (o *Pokedex) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Pokedex) GetPokemonEntries() []PokemonEntry {
	if o == nil {
		return []PokemonEntry{}
	}
	return o.PokemonEntries
}

func (o *Pokedex) GetRegion() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.Region
}
