// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PokemonSpeciesDexEntry - An entry of a Pokemon species seen in the Pokedex.
type PokemonSpeciesDexEntry struct {
	// The index number of the Pokedex entry.
	EntryNumber *int64            `json:"entry_number,omitempty"`
	Pokedex     *NamedAPIResource `json:"pokedex,omitempty"`
}

func (o *PokemonSpeciesDexEntry) GetEntryNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.EntryNumber
}

func (o *PokemonSpeciesDexEntry) GetPokedex() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Pokedex
}
