// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonAbility struct {
	Ability  *Ability `json:"ability,omitempty"`
	IsHidden *bool    `json:"is_hidden,omitempty"`
	Slot     *int64   `json:"slot,omitempty"`
}
