// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonEntry struct {
	// The index number within the Pokédex.
	EntryNumber    *int64            `json:"entry_number,omitempty"`
	PokemonSpecies *NamedAPIResource `json:"pokemon_species,omitempty"`
}
