// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PokemonSpeciesEvolutionChain struct {
}

// PokemonSpecies - Successful response
type PokemonSpecies struct {
	BaseHappiness        *int                          `json:"base_happiness,omitempty"`
	CaptureRate          *int                          `json:"capture_rate,omitempty"`
	Color                *PokemonColor                 `json:"color,omitempty"`
	EggGroups            []EggGroup                    `json:"egg_groups,omitempty"`
	EvolutionChain       *PokemonSpeciesEvolutionChain `json:"evolution_chain,omitempty"`
	EvolvesFromSpecies   *PokemonSpecies               `json:"evolves_from_species,omitempty"`
	FlavorTextEntries    []FlavorText                  `json:"flavor_text_entries,omitempty"`
	FormDescriptions     []Description                 `json:"form_descriptions,omitempty"`
	FormsSwitchable      *bool                         `json:"forms_switchable,omitempty"`
	GenderRate           *int                          `json:"gender_rate,omitempty"`
	Genera               []Genus                       `json:"genera,omitempty"`
	Generation           *Generation                   `json:"generation,omitempty"`
	GrowthRate           *GrowthRate                   `json:"growth_rate,omitempty"`
	Habitat              *PokemonHabitat               `json:"habitat,omitempty"`
	HasGenderDifferences *bool                         `json:"has_gender_differences,omitempty"`
	HatchCounter         *int                          `json:"hatch_counter,omitempty"`
	ID                   *int                          `json:"id,omitempty"`
	IsBaby               *bool                         `json:"is_baby,omitempty"`
	Name                 *string                       `json:"name,omitempty"`
	Names                []Name                        `json:"names,omitempty"`
	Order                *int                          `json:"order,omitempty"`
	PalParkEncounters    []PalParkEncounterArea        `json:"pal_park_encounters,omitempty"`
	PokedexNumbers       []PokemonSpeciesDexEntry      `json:"pokedex_numbers,omitempty"`
	Shape                *PokemonShape                 `json:"shape,omitempty"`
	Varieties            []PokemonSpeciesVariety       `json:"varieties,omitempty"`
}
