// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Region - Successful response
type Region struct {
	ID             int                `json:"id"`
	Locations      []NamedAPIResource `json:"locations"`
	MainGeneration NamedAPIResource   `json:"main_generation"`
	Name           string             `json:"name"`
	Names          []Name             `json:"names"`
	Pokedexes      []NamedAPIResource `json:"pokedexes"`
	VersionGroups  []NamedAPIResource `json:"version_groups"`
}
