// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Stat - Successful response
type Stat struct {
	AffectingMoves   *MoveStatAffectSets   `json:"affecting_moves,omitempty"`
	AffectingNatures *NatureStatAffectSets `json:"affecting_natures,omitempty"`
	GameIndex        int                   `json:"game_index"`
	ID               int                   `json:"id"`
	IsBattleOnly     *bool                 `json:"is_battle_only,omitempty"`
	Name             string                `json:"name"`
}
