// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SuperContestEffect - Successful response
type SuperContestEffect struct {
	Appeal            int                `json:"appeal"`
	FlavorTextEntries []FlavorText       `json:"flavor_text_entries"`
	ID                int                `json:"id"`
	Moves             []NamedAPIResource `json:"moves"`
}
