// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TypeDamageRelationsDoubleDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelationsDoubleDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelationsHalfDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelationsHalfDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelationsNoDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelationsNoDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

type TypeDamageRelations struct {
	DoubleDamageFrom []TypeDamageRelationsDoubleDamageFrom `json:"double_damage_from,omitempty"`
	DoubleDamageTo   []TypeDamageRelationsDoubleDamageTo   `json:"double_damage_to,omitempty"`
	HalfDamageFrom   []TypeDamageRelationsHalfDamageFrom   `json:"half_damage_from,omitempty"`
	HalfDamageTo     []TypeDamageRelationsHalfDamageTo     `json:"half_damage_to,omitempty"`
	NoDamageFrom     []TypeDamageRelationsNoDamageFrom     `json:"no_damage_from,omitempty"`
	NoDamageTo       []TypeDamageRelationsNoDamageTo       `json:"no_damage_to,omitempty"`
}

type TypeGameIndicesGeneration struct {
	// The generation this game index is related to.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the generation.
	URL *string `json:"url,omitempty"`
}

type TypeGameIndices struct {
	// The internal id of an api resource within game data.
	GameIndex  *int                       `json:"game_index,omitempty"`
	Generation *TypeGameIndicesGeneration `json:"generation,omitempty"`
}

type TypeGeneration struct {
	// The generation this type originated in.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for this generation.
	URL *string `json:"url,omitempty"`
}

type TypeMoveDamageClass struct {
	// The name of this move damage class.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for this move damage class.
	URL *string `json:"url,omitempty"`
}

type TypeNamesLanguage struct {
	// The name of the language.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the language.
	URL *string `json:"url,omitempty"`
}

type TypeNames struct {
	Language *TypeNamesLanguage `json:"language,omitempty"`
	// The localized name for an API resource in a specific language.
	Name *string `json:"name,omitempty"`
}

type TypePokemon struct {
	Slot *int64 `json:"slot,omitempty"`
}

// Type - Successful response
type Type struct {
	DamageRelations *TypeDamageRelations `json:"damage_relations,omitempty"`
	GameIndices     []TypeGameIndices    `json:"game_indices,omitempty"`
	Generation      *TypeGeneration      `json:"generation,omitempty"`
	// The identifier for this type resource.
	ID              *int                 `json:"id,omitempty"`
	MoveDamageClass *TypeMoveDamageClass `json:"move_damage_class,omitempty"`
	// The name for this type resource.
	Name    *string       `json:"name,omitempty"`
	Names   []TypeNames   `json:"names,omitempty"`
	Pokemon []TypePokemon `json:"pokemon,omitempty"`
}
