// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DoubleDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *DoubleDamageFrom) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DoubleDamageFrom) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type DoubleDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *DoubleDamageTo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DoubleDamageTo) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type HalfDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *HalfDamageFrom) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *HalfDamageFrom) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type HalfDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *HalfDamageTo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *HalfDamageTo) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type NoDamageFrom struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *NoDamageFrom) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *NoDamageFrom) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type NoDamageTo struct {
	// The name of the related type.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the related type.
	URL *string `json:"url,omitempty"`
}

func (o *NoDamageTo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *NoDamageTo) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type DamageRelations struct {
	DoubleDamageFrom []DoubleDamageFrom `json:"double_damage_from,omitempty"`
	DoubleDamageTo   []DoubleDamageTo   `json:"double_damage_to,omitempty"`
	HalfDamageFrom   []HalfDamageFrom   `json:"half_damage_from,omitempty"`
	HalfDamageTo     []HalfDamageTo     `json:"half_damage_to,omitempty"`
	NoDamageFrom     []NoDamageFrom     `json:"no_damage_from,omitempty"`
	NoDamageTo       []NoDamageTo       `json:"no_damage_to,omitempty"`
}

func (o *DamageRelations) GetDoubleDamageFrom() []DoubleDamageFrom {
	if o == nil {
		return nil
	}
	return o.DoubleDamageFrom
}

func (o *DamageRelations) GetDoubleDamageTo() []DoubleDamageTo {
	if o == nil {
		return nil
	}
	return o.DoubleDamageTo
}

func (o *DamageRelations) GetHalfDamageFrom() []HalfDamageFrom {
	if o == nil {
		return nil
	}
	return o.HalfDamageFrom
}

func (o *DamageRelations) GetHalfDamageTo() []HalfDamageTo {
	if o == nil {
		return nil
	}
	return o.HalfDamageTo
}

func (o *DamageRelations) GetNoDamageFrom() []NoDamageFrom {
	if o == nil {
		return nil
	}
	return o.NoDamageFrom
}

func (o *DamageRelations) GetNoDamageTo() []NoDamageTo {
	if o == nil {
		return nil
	}
	return o.NoDamageTo
}

type TypeSchemasGeneration struct {
	// The generation this game index is related to.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the generation.
	URL *string `json:"url,omitempty"`
}

func (o *TypeSchemasGeneration) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TypeSchemasGeneration) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type GameIndices struct {
	// The internal id of an api resource within game data.
	GameIndex  *int                   `json:"game_index,omitempty"`
	Generation *TypeSchemasGeneration `json:"generation,omitempty"`
}

func (o *GameIndices) GetGameIndex() *int {
	if o == nil {
		return nil
	}
	return o.GameIndex
}

func (o *GameIndices) GetGeneration() *TypeSchemasGeneration {
	if o == nil {
		return nil
	}
	return o.Generation
}

type TypeGeneration struct {
	// The generation this type originated in.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for this generation.
	URL *string `json:"url,omitempty"`
}

func (o *TypeGeneration) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TypeGeneration) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type TypeMoveDamageClass struct {
	// The name of this move damage class.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for this move damage class.
	URL *string `json:"url,omitempty"`
}

func (o *TypeMoveDamageClass) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TypeMoveDamageClass) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type TypeLanguage struct {
	// The name of the language.
	Name *string `json:"name,omitempty"`
	// The URL of the API endpoint for the language.
	URL *string `json:"url,omitempty"`
}

func (o *TypeLanguage) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TypeLanguage) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

type TypeNames struct {
	Language *TypeLanguage `json:"language,omitempty"`
	// The localized name for an API resource in a specific language.
	Name *string `json:"name,omitempty"`
}

func (o *TypeNames) GetLanguage() *TypeLanguage {
	if o == nil {
		return nil
	}
	return o.Language
}

func (o *TypeNames) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

type TypePokemon struct {
	Slot *int64 `json:"slot,omitempty"`
}

func (o *TypePokemon) GetSlot() *int64 {
	if o == nil {
		return nil
	}
	return o.Slot
}

type Type struct {
	DamageRelations *DamageRelations `json:"damage_relations,omitempty"`
	GameIndices     []GameIndices    `json:"game_indices,omitempty"`
	Generation      *TypeGeneration  `json:"generation,omitempty"`
	// The identifier for this type resource.
	ID              *int                 `json:"id,omitempty"`
	MoveDamageClass *TypeMoveDamageClass `json:"move_damage_class,omitempty"`
	// The name for this type resource.
	Name    *string       `json:"name,omitempty"`
	Names   []TypeNames   `json:"names,omitempty"`
	Pokemon []TypePokemon `json:"pokemon,omitempty"`
}

func (o *Type) GetDamageRelations() *DamageRelations {
	if o == nil {
		return nil
	}
	return o.DamageRelations
}

func (o *Type) GetGameIndices() []GameIndices {
	if o == nil {
		return nil
	}
	return o.GameIndices
}

func (o *Type) GetGeneration() *TypeGeneration {
	if o == nil {
		return nil
	}
	return o.Generation
}

func (o *Type) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Type) GetMoveDamageClass() *TypeMoveDamageClass {
	if o == nil {
		return nil
	}
	return o.MoveDamageClass
}

func (o *Type) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Type) GetNames() []TypeNames {
	if o == nil {
		return nil
	}
	return o.Names
}

func (o *Type) GetPokemon() []TypePokemon {
	if o == nil {
		return nil
	}
	return o.Pokemon
}
