// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VersionGameIndex struct {
	// The internal id of the game used in generation VI and VII to identify different
	// versions of the same Pokémon species.
	//
	GameIndex *int64            `json:"game_index,omitempty"`
	Version   *NamedAPIResource `json:"version,omitempty"`
}
