// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VersionGroup struct {
	Generation       NamedAPIResource   `json:"generation"`
	ID               int                `json:"id"`
	MoveLearnMethods []NamedAPIResource `json:"move_learn_methods"`
	Name             string             `json:"name"`
	Order            int                `json:"order"`
	Pokedexes        []NamedAPIResource `json:"pokedexes"`
	Regions          []NamedAPIResource `json:"regions"`
	Versions         []NamedAPIResource `json:"versions"`
}

func (o *VersionGroup) GetGeneration() NamedAPIResource {
	if o == nil {
		return NamedAPIResource{}
	}
	return o.Generation
}

func (o *VersionGroup) GetID() int {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *VersionGroup) GetMoveLearnMethods() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.MoveLearnMethods
}

func (o *VersionGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *VersionGroup) GetOrder() int {
	if o == nil {
		return 0
	}
	return o.Order
}

func (o *VersionGroup) GetPokedexes() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.Pokedexes
}

func (o *VersionGroup) GetRegions() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.Regions
}

func (o *VersionGroup) GetVersions() []NamedAPIResource {
	if o == nil {
		return []NamedAPIResource{}
	}
	return o.Versions
}
