// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// VersionGroup - Successful response
type VersionGroup struct {
	Generation       NamedAPIResource   `json:"generation"`
	ID               int                `json:"id"`
	MoveLearnMethods []NamedAPIResource `json:"move_learn_methods"`
	Name             string             `json:"name"`
	Order            int                `json:"order"`
	Pokedexes        []NamedAPIResource `json:"pokedexes"`
	Regions          []NamedAPIResource `json:"regions"`
	Versions         []NamedAPIResource `json:"versions"`
}
