// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VersionGameIndex struct {
	// The internal id of the game used in generation VI and VII to identify different
	// versions of the same Pokémon species.
	//
	GameIndex *int64            `json:"game_index,omitempty"`
	Version   *NamedAPIResource `json:"version,omitempty"`
}

func (o *VersionGameIndex) GetGameIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.GameIndex
}

func (o *VersionGameIndex) GetVersion() *NamedAPIResource {
	if o == nil {
		return nil
	}
	return o.Version
}
