// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Version - Successful response
type Version struct {
	ID           int              `json:"id"`
	Name         string           `json:"name"`
	Names        []Name           `json:"names"`
	VersionGroup NamedAPIResource `json:"version_group"`
}
